import {
  Loader2,
  LucideProps,
  User,
  Settings,
  Shield,
  LayoutDashboard,
  LogOut,
  ChevronRight,
  ChevronLeft,
  Search,
  Bell,
  Mail,
  Lock,
  Eye,
  EyeOff,
  MoreVertical,
  Edit,
  Trash,
  CheckCircle2,
  AlertCircle,
  X,
  CreditCard,
  CreditCardIcon,
} from "lucide-react"

export const Icons = {
  spinner: Loader2,
  user: User,
  settings: Settings,
  shield: Shield,
  dashboard: LayoutDashboard,
  logout: LogOut,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  search: Search,
  bell: Bell,
  mail: Mail,
  lock: Lock,
  eye: Eye,
  eyeOff: EyeOff,
  moreVertical: MoreVertical,
  edit: Edit,
  trash: Trash,
  checkCircle: CheckCircle2,
  alertCircle: AlertCircle,
  close: X,
  payment: CreditCard,
  billing: CreditCardIcon,
}

export type Icon = typeof Loader2
